# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Button, PhotoImage, messagebox, NW

from PIL import Image, ImageTk

from backend.controlbackend import login
from backend.controlbackend import signup_account
from middleware.account import Accounts


class SignUpGUI:

    def __init__(self, root):
        self.root = root
        self.root.geometry("640x455")
        self.root.configure(bg="#EBF2FA")
        self.root.title('Sign Up Page')
        self.root.resizable(False, False)
        self.image_image_1 = None
        self.image_image_2 = None
        self.image_image_3 = None
        self.entry_image_1 = None
        self.entry_image_3 = None
        self.entry_image_2 = None
        self.button_image_2 = None
        self.button_image_1 = None
        self.init_ui()

    def init_ui(self):
        # ----------------------------------------------
        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\chien\PycharmProjects\pythonProject\frontend\assets\frame1")

        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)

        # ------------------------------------------------------

        # --------------------------------------------------
        canvas = Canvas(
            self.root,
            bg="#EBF2FA",
            height=455,
            width=640,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )
        canvas.place(x=0, y=0)

        self.image_image_1 = PhotoImage(
            file=relative_to_assets('image_1.png'))
        canvas.create_image(
            0.0,
            0.0,
            image=self.image_image_1,
            anchor=NW
        )

        self.image_image_2 = PhotoImage(
            file=relative_to_assets('image_2.png'))
        canvas.create_image(
            10.0,
            227.0,
            image=self.image_image_2,
            anchor=NW
        )

        self.image_image_3 = PhotoImage(
            file=relative_to_assets('image_3.png'))
        canvas.create_image(
            10.0,
            10.0,
            image=self.image_image_3,
            anchor=NW
        )

        canvas.create_text(
            360.0,
            74.0,
            anchor=NW,
            text="Sign Up",
            fill="#000000",
            font=("Segoe UI Bold", 24 * -1)
        )

        # ------------------------------------------------------------------------
        # set click clear field 
        def on_enter(e):
            entry_user.delete(0, 'end')

        def on_leave(e):
            username = entry_user.get()
            if username == '':
                entry_user.insert(0, 'Username')

        self.entry_image_1 = PhotoImage(
            file=relative_to_assets('entry_1.png'))
        canvas.create_image(
            440.0,
            154.0,
            image=self.entry_image_1
        )
        entry_user = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        entry_user.place(
            x=295.0,
            y=136.0,
            width=290.0,
            height=34.0
        )
        # suggest field entry username
        entry_user.insert(0, 'Username')
        entry_user.bind('<FocusIn>', on_enter)
        entry_user.bind('<FocusOut>', on_leave)

        # --------------------------------------------------------------
        # set click to clear field
        def on_enter(e):
            entry_passw.delete(0, 'end')

        def on_leave(e):
            password = entry_passw.get()
            if password == '':
                entry_passw.insert(0, 'Password')

        self.entry_image_2 = PhotoImage(
            file=relative_to_assets('entry_2.png'))

        canvas.create_image(
            440.0,
            227.0,
            image=self.entry_image_2
        )
        entry_passw = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        entry_passw.place(
            x=295.0,
            y=209.0,
            width=290.0,
            height=34.0
        )
        # suggest field entry password
        entry_passw.insert(0, 'Password')
        entry_passw.bind('<FocusIn>', on_enter)
        entry_passw.bind('<FocusOut>', on_leave)

        # -----------------------------------------------------------------
        # set click to clear field
        def on_enter(e):
            entry_conf_passw.delete(0, 'end')

        def on_leave(e):
            conf_password = entry_conf_passw.get()
            if conf_password == '':
                entry_conf_passw.insert(0, 'Confirm Password')

        self.entry_image_3 = PhotoImage(
            file=relative_to_assets('entry_3.png'))

        canvas.create_image(
            441.0,
            300.0,
            image=self.entry_image_3
        )
        entry_conf_passw = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        entry_conf_passw.place(
            x=296.0,
            y=282.0,
            width=290.0,
            height=34.0
        )

        entry_conf_passw.insert(0, 'Confirm Password')
        entry_conf_passw.bind('<FocusIn>', on_enter)
        entry_conf_passw.bind('<FocusOut>', on_leave)

        # -------------------------------------------------------------
        # define function sign up add to database
        def signup():
            username = entry_user.get()
            password = entry_passw.get()
            conf_password = entry_conf_passw.get()
            # print(username, password, conf_password)
            add_acc = Accounts(
                username=username,
                password=password
            )

            if password == conf_password:
                result = signup_account(add_acc)
                if result is not None:
                    messagebox.showinfo('Signup', 'Successful sign up')

                else:
                    messagebox.showerror('Invalid', 'Both password did not match')

        # -----------------------------------------------------------------
        def signin_page():
            # neewscr = Tk()
            self.root.resizable(False, False)
            self.root.geometry("640x455")
            self.root.configure(bg="#EBF2FA")
            self.root.title('Sign In Page')
            # --------------------------------------------------------------------------------------------
            OUTPUT_PATH = Path(__file__).parent
            ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\chien\PycharmProjects\pythonProject\frontend\assets\frame0")

            def relative_to_assets(path: str) -> Path:
                return ASSETS_PATH / Path(path)

            # ----------------------------------------------------------------------------------------------------

            # ---------------------------------------------------
            canvas1 = Canvas(
                self.root,
                bg="#EBF2FA",
                height=455,
                width=640,
                bd=0,
                highlightthickness=0,
                relief="ridge"
            )

            canvas1.place(x=0, y=0)

            self.image_image_1 = PhotoImage(
                file=relative_to_assets('image_1.png'))
            canvas1.create_image(
                0.0,
                0.0,
                image=self.image_image_1,
                anchor=NW
            )

            self.image_image_2 = PhotoImage(
                file=relative_to_assets('image_2.png'))
            canvas1.create_image(
                10.0,
                227.0,
                image=self.image_image_2,
                anchor=NW
            )

            self.image_image_3 = PhotoImage(
                file=relative_to_assets('image_3.png'))
            canvas1.create_image(
                10.0,
                10.0,
                image=self.image_image_3,
                anchor=NW
            )

            canvas1.create_text(
                395.0,
                74.0,
                anchor="nw",
                text="Sign In",
                fill="#000000",
                font=("Segoe UI Bold", 24 * -1)
            )

            # --------------------------------------------------

            # --------------------------------------------------------------------
            def on_enter(e):
                entry_user.delete(0, 'end')

            def on_leave(e):
                username = entry_user.get()
                if username == '':
                    entry_user.insert(0, 'Username')

            self.entry_image_1 = PhotoImage(
                file=relative_to_assets('entry_1.png'))
            canvas1.create_image(
                440.0,
                169.0,
                image=self.entry_image_1
            )
            entry_user = Entry(
                bd=0,
                bg="#FFFFFF",
                fg="#000716",
                highlightthickness=0
            )
            entry_user.place(
                x=295.0,
                y=151.0,
                width=290.0,
                height=34.0
            )
            # suggest field entry username
            entry_user.insert(0, 'Username')
            entry_user.bind('<FocusIn>', on_enter)
            entry_user.bind('<FocusOut>', on_leave)

            # ----------------------------------------------------------
            #
            def on_enter(e):
                entry_passw.delete(0, 'end')

            def on_leave(e):
                password = entry_passw.get()
                if password == '':
                    entry_passw.insert(0, 'Password')

            self.entry_image_2 = PhotoImage(
                file=relative_to_assets('entry_2.png'))
            canvas1.create_image(
                440.0,
                242.0,
                image=self.entry_image_2
            )
            entry_passw = Entry(
                bd=0,
                bg="#FFFFFF",
                fg="#000716",
                highlightthickness=0
            )
            entry_passw.place(
                x=295.0,
                y=224.0,
                width=290.0,
                height=34.0
            )
            # suggest field entry password
            entry_passw.insert(0, 'Password')
            entry_passw.bind('<FocusIn>', on_enter)
            entry_passw.bind('<FocusOut>', on_leave)

            # ----------------------------------------------------------
            # event click button signin
            def sign_in():
                acc = Accounts(
                    username=entry_user.get(),
                    password=entry_passw.get()
                )
                result = login(acc)
                if result is not None:
                    messagebox.showinfo('Welcome', 'Hello {}'.format(entry_user.get()))
                else:
                    messagebox.showerror('Ivalid', 'Username or password incorrect')

            def sign_up():
                # window = Tk()
                exa = SignUpGUI(self.root)
                self.root.mainloop()

            # -------------------------------------------------------------------------
            self.button_image_1 = PhotoImage(
                file=relative_to_assets('button_1.png'))
            button_sign_in = Button(
                image=self.button_image_1,
                borderwidth=0,
                highlightthickness=0,
                command=sign_in,
                relief="flat"
            )
            button_sign_in.place(
                x=323.0,
                y=287.0,
                width=234.0,
                height=43.0
            )

            # -----------------------------------------------------------------------
            self.button_image_2 = PhotoImage(
                file=relative_to_assets('button_2.png'))
            button_sign_up = Button(
                image=self.button_image_2,
                borderwidth=0,
                highlightthickness=0,
                command=sign_up,
                relief="flat",
                cursor='hand2'
            )
            button_sign_up.place(
                x=355.0,
                y=426.0,
                width=172.0,
                height=17.0
            )

        # -----------------------------------------------------------------
        self.button_image_1 = PhotoImage(
            file=relative_to_assets('button_1.png'))

        button_1 = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=signup,
            relief="flat"
        )
        button_1.place(
            x=324.0,
            y=338.0,
            width=234.0,
            height=43.0
        )

        # ------------------------------------------------------------------------------------------------------
        self.button_image_2 = PhotoImage(
            file=relative_to_assets('button_2.png'))

        button_2 = Button(
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=signin_page,
            relief="flat",
            cursor='hand2'
        )
        button_2.place(
            x=355.0,
            y=426.0,
            width=172.0,
            height=17.0
        )


# ----------------------------------------------------------------------------------------------------------


# main function of class
if __name__ == '__main__':
    root = Tk()
    ex = SignUpGUI(root)
    root.mainloop()
