# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Button, PhotoImage, messagebox, NW

from PIL import Image, ImageTk

from backend.controlbackend import login
from frontend.signup import SignUpGUI
from middleware.account import Accounts


class SignInGUI:

    def __init__(self, root):
        self.root = root
        self.root.resizable(False, False)
        self.root.geometry("640x455")
        self.root.configure(bg="#EBF2FA")
        self.root.title('Sign In Page')
        self.button_image_2 = None
        self.button_image_1 = None
        self.entry_image_2 = None
        self.image_image_3 = None
        self.image_image_2 = None
        self.image_image_1 = None
        self.entry_image_1 = None
        self.init_ui()

    def init_ui(self):
        # --------------------------------------------------------------------------------------------
        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\chien\PycharmProjects\pythonProject\frontend\assets\frame0")

        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)

        # ----------------------------------------------------------------------------------------------------

        # ---------------------------------------------------
        canvas = Canvas(
            self.root,
            bg="#EBF2FA",
            height=455,
            width=640,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )

        canvas.place(x=0, y=0)

        self.image_image_1 = PhotoImage(
            file=relative_to_assets('image_1.png'))
        canvas.create_image(
            0.0,
            0.0,
            image=self.image_image_1,
            anchor=NW
        )

        self.image_image_2 = PhotoImage(
            file=relative_to_assets('image_2.png'))
        canvas.create_image(
            10.0,
            227.0,
            image=self.image_image_2,
            anchor=NW
        )

        self.image_image_3 = PhotoImage(
            file=relative_to_assets('image_3.png'))
        canvas.create_image(
            10.0,
            10.0,
            image=self.image_image_3,
            anchor=NW
        )

        canvas.create_text(
            395.0,
            74.0,
            anchor="nw",
            text="Sign In",
            fill="#000000",
            font=("Segoe UI Bold", 24 * -1)
        )

        # --------------------------------------------------

        # --------------------------------------------------------------------
        def on_enter(e):
            entry_user.delete(0, 'end')

        def on_leave(e):
            username = entry_user.get()
            if username == '':
                entry_user.insert(0, 'Username')

        self.entry_image_1 = PhotoImage(
            file=relative_to_assets('entry_1.png'))
        canvas.create_image(
            440.0,
            169.0,
            image=self.entry_image_1
        )
        entry_user = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        entry_user.place(
            x=295.0,
            y=151.0,
            width=290.0,
            height=34.0
        )
        # suggest field entry username
        entry_user.insert(0, 'Username')
        entry_user.bind('<FocusIn>', on_enter)
        entry_user.bind('<FocusOut>', on_leave)

        # ----------------------------------------------------------
        #
        def on_enter(e):
            entry_passw.delete(0, 'end')

        def on_leave(e):
            password = entry_passw.get()
            if password == '':
                entry_passw.insert(0, 'Password')

        self.entry_image_2 = PhotoImage(
            file=relative_to_assets('entry_2.png'))
        canvas.create_image(
            440.0,
            242.0,
            image=self.entry_image_2
        )
        entry_passw = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        entry_passw.place(
            x=295.0,
            y=224.0,
            width=290.0,
            height=34.0
        )
        # suggest field entry password
        entry_passw.insert(0, 'Password')
        entry_passw.bind('<FocusIn>', on_enter)
        entry_passw.bind('<FocusOut>', on_leave)

        # ----------------------------------------------------------
        # event click button signin
        def sign_in():
            acc = Accounts(
                username=entry_user.get(),
                password=entry_passw.get()
            )
            result = login(acc)
            if result is not None:
                messagebox.showinfo('Welcome', 'Hello {}'.format(entry_user.get()))
            else:
                messagebox.showerror('Ivalid', 'Username or password incorrect')

        def sign_up():
            # window = Tk()
            exa = SignUpGUI(window)
            window.mainloop()

        # -------------------------------------------------------------------------
        self.button_image_1 = PhotoImage(
            file=relative_to_assets('button_1.png'))
        button_sign_in = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=sign_in,
            relief="flat"
        )
        button_sign_in.place(
            x=323.0,
            y=287.0,
            width=234.0,
            height=43.0
        )

        # -----------------------------------------------------------------------
        self.button_image_2 = PhotoImage(
            file=relative_to_assets('button_2.png'))
        button_sign_up = Button(
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=sign_up,
            relief="flat",
            cursor='hand2'
        )
        button_sign_up.place(
            x=355.0,
            y=426.0,
            width=172.0,
            height=17.0
        )


# -------------------------------------------------------------------------------
if __name__ == '__main__':
    window = Tk()
    tk = SignInGUI(window)
    window.mainloop()
